[package]
name = "compositor-rs"
description = "The Compositor application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "compositor-rs"
path = "src/main.rs"

[dependencies]
compositor-rs-core.workspace = true
compositor-rs-pixels.workspace = true
compositor-rs-render.workspace = true
compositor-rs-session.workspace = true
compositor-rs-io.workspace = true
compositor-rs-ui.workspace = true
gpui-kit = "0.7"
futures = "0.3"
log.workspace = true
env_logger.workspace = true
