[package]
name = "compositor-ui"
description = "The Compositor editor's gpui interface"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
compositor-core.workspace = true
compositor-pixels.workspace = true
compositor-render.workspace = true
compositor-session.workspace = true
compositor-io.workspace = true
gpui-kit = "0.7"
rustc-hash.workspace = true
parking_lot.workspace = true
log.workspace = true
