[package]
name = "compositor-rs-io"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
compositor-rs-core.workspace = true
compositor-rs-pixels.workspace = true
compositor-rs-session.workspace = true
image.workspace = true
png.workspace = true
flate2.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
notify.workspace = true
resvg.workspace = true
usvg.workspace = true
rawler.workspace = true
thiserror.workspace = true
log.workspace = true
parking_lot.workspace = true
half.workspace = true
rustc-hash.workspace = true
sha2.workspace = true
